version: '3'
services:
  cassandra:
    image: cassandra:3.11.3
    container_name: ha_bioinformatica_cassandra
    hostname: cassandra
    environment:
      SEED: cassandra
      LISTEN_ADDRESS: cassandra
      BROADCAST_ADDRESS: cassandra
      START_RPC: "true"
      CASSANDRA_START_RPC: "true"
      ENABLE_THRIFT: "true"
      RPC_ADDRESS: 0.0.0.0
    ports:
      - 9042:9042
      - 7199:7199
      - 9160:9160
    volumes:
      - ./data-cassandra:/var/lib/cassandra
      - ./cassandra/ha_bioinformatica.cql:/ha_bioinformatica.cql
      - ./cassandra-init.sh:/cassandra-init.sh
    command: sh /cassandra-init.sh

  spark-master:
    image: gettyimages/spark
    container_name: ha_bioinformatica_spark_master
    hostname: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    links:
      - cassandra:cassandra
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./conf-spark/master:/conf
      - ./data-spark:/tmp/data
      - ./src:/src

  spark-worker:
    image: gettyimages/spark
    container_name: ha_bioinformatica_spark_worker
    hostname: spark-worker
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 6g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - spark-master
      - cassandra:cassandra
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./conf-spark/worker:/conf
      - ./data-spark:/tmp/data
